language: node_js
node_js:
  - "8"

branches:
  only:
    - master

services:
# enable docker service inside travis
  - docker

sudo: false

cache:
  directories:
    - node_modules

before_install:
  - npm config set spin false

install:
  - npm install

script:
  - npm run lint
  - npm test -- --coverage
  - npm run build

after_success:
  - node config/deployArtifacts
  - npm install -g codecov
  - bash <(curl -s https://codecov.io/bash)
  - bash config/buildDockerImage.sh

notifications:
  slack: 3blades:ycSapbO8XmfCrdT0vX2yw090

env:
  - $DOCKER_IMAGE_NAME="3blades/react-frontend"
