language: node_js
node_js:
  - "8"

branches:
  only:
    - master

sudo: false

addons:
    code_climate:
        repo_token: $CODE_CLIMATE

cache:
  directories:
    - node_modules

before_install:
  - npm config set spin false

install:
  - npm install

script:
  - npm test -- --coverage

after_success:
  - npm install -g codecov
  - bash <(curl -s https://codecov.io/bash)

notifications:
  slack: 3blades:ycSapbO8XmfCrdT0vX2yw090
