coverage:
  precision: 2
  round: down
  range: "70...100"

  notify:
    slack:
      default:
        url: https://hooks.slack.com/services/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
        attachments: "sunburst, diff"

  status:
    project:
      default:
        target: auto

    patch:
      default:
        target: auto

comment:
  layout: "header, diff, changes, sunburst, uncovered, tree"
  behavior: default
