export const MOVE_BOARD_ELEMENT = 'MOVE_BOARD_ELEMENT';
export const ADD_BOARD = 'ADD_BOARD';
export const DELETE_BOARD = 'DELETE_BOARD';
export const DELETE_BOARD_ELEMENT = 'DELETE_BOARD_ELEMENT';
export const ADD_BOARD_ELEMENT = 'ADD_BOARD_ELEMENT';

export const RENAME_PROJECT = 'RENAME_PROJECT';
export const CHANGE_DESCRIPTION = 'CHANGE_DESCRIPTION';
export const TOGGLE_VISIBILITY = 'TOGGLE_VISIBILITY';
export const DELETE_PROJECT = 'DELETE_PROJECT';

export const ADD_COLLABORATOR = 'ADD_COLLABORATOR';
export const DELETE_COLLABORATOR = 'DELETE_COLLABORATOR';
export const CHANGE_COLLABORATOR_ROLE = 'CHANGE_COLLABORATOR_ROLE';

export const DELETE_FILE = 'DELETE_FILE';
export const EDIT_FILE = 'EDIT_FILE';
export const RENAME_FILE = 'RENAME_FILE';
export const DUPLICATE_FILE = 'DUPLICATE_FILE';

export const DELETE_WORKSPACE = 'DELETE_WORKSPACE';
export const START_WORKSPACE = 'START_WORKSPACE';
export const STOP_WORKSPACE = 'STOP_WORKSPACE';

export const DELETE_JOB = 'DELETE_JOB';
export const START_JOB = 'START_JOB';
export const STOP_JOB = 'STOP_JOB';

export const DELETE_MODEL = 'DELETE_MODEL';
export const START_MODEL = 'START_MODEL';
export const STOP_MODEL = 'STOP_MODEL';
